### ISSUE TITLE
CheckM not compiling with pip install --user

### ISSUE THREAD

**Issue by piyuranjan** [Ecogenomics/CheckM#59] opened 2016-04-14 23:19 UTC
Hi,
I don't have root permissions, so tried `pip install --user checkm-genome` for a local installation which ended up in the following error (more information in the log file attached):

> Traceback (most recent call last):
>   File "/usr/local/bin/pip", line 11, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python2.7/site-packages/pip/\__init\__.py", line 185, in main
>     return command.main(cmd_args)
>   File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 161, in main
>     text = '\n'.join(complete_log)
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 40: ordinal not in range(128)
> 

[checkmCompile.log.txt](https://github.com/Ecogenomics/CheckM/files/220094/checkmCompile.log.txt)

Running checkm after a failed compile says:

> [pranjan6@bacphile2 Thu Apr 14 17:58:15 BinningMetabat]$ checkm
> Traceback (most recent call last):
>   File "/usr/local/bin/checkm", line 37, in <module>
>     from checkm import main
>   File "/projects/home/pranjan6/.local/lib/python2.7/site-packages/checkm/main.py", line 49, in <module>
>     from checkm.plot.gcPlots import GcPlots
>   File "/projects/home/pranjan6/.local/lib/python2.7/site-packages/checkm/plot/gcPlots.py", line 24, in <module>
>     from AbstractPlot import AbstractPlot
>   File "/projects/home/pranjan6/.local/lib/python2.7/site-packages/checkm/plot/AbstractPlot.py", line 22, in <module>
>     from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
>   File "/projects/home/pranjan6/.local/lib/python2.7/site-packages/matplotlib/\__init\__.py", line 124, in <module>
>     from matplotlib.rcsetup import (defaultParams,
>   File "/projects/home/pranjan6/.local/lib/python2.7/site-packages/matplotlib/rcsetup.py", line 34, in <module>
>     from cycler import Cycler, cycler as ccycler
> ImportError: No module named cycler

The package numpy installed fine using `pip install --user --upgrade numpy`.
Any leads on using this without root?

Thanks!

**Comment by dparks1134** [comment] 2016-04-14 23:33
From the error log it appear the issue is with pysam. Can you try installing this separately and see what happens? If this doesn't install, the authors of pysam should be able to help.

**Comment by piyuranjan** [comment] 2016-04-15 00:20
Thanks for checking this.
It does look like the problem is with installation of pysam. When I tried installing pysam with `pip install --user --upgrade pysam` it did throw the same error. The authors of pysam had a similar issue reported [https://github.com/pysam-developers/pysam/issues/262](url) and I tried installing htslib seperately with setting up the recommended environment variables. This again didn't solve the issue. Installing pysam after downloading the package with `python setup.py install` is also not working.

Is there a way that I can undo the changes made by this bad compilation? My server already had an older version of CheckM running, but when I tried upgrading to the latest version in `~/.local`, the bad compilation made the original version unavailable for me.

**Comment by piyuranjan** [comment] 2016-04-15 00:43
An update: Installed a previous version of pysam (pysam-0.8.4) successfully. Downloaded CheckM (CheckM-1.0.5) and tried installing manually and finished without errors. Still, while using CheckM the path for the executable comes from `/usr/local/bin/checkm` and gives the same error.
The instance installed in `~/.local/bin/` gives the following error:

> $ /projects/home/pranjan6/.local/bin/checkm 
> Traceback (most recent call last):
>   File "/projects/home/pranjan6/.local/bin/checkm", line 36, in <module>
>     from checkm import main
>   File "/projects/home/pranjan6/.local/lib/python2.6/site-packages/checkm/main.py", line 25, in <module>
>     from checkm.defaultValues import DefaultValues
>   File "/projects/home/pranjan6/.local/lib/python2.6/site-packages/checkm/defaultValues.py", line 34
>     MARKERS_TO_EXCLUDE = {'TIGR00398', 'TIGR00399'}
>                                      ^
> SyntaxError: invalid syntax
>

**Comment by dparks1134** [comment] 2016-04-19 02:09
Sorry for the delayed response. I'm a little confused at your installation since you seem to be indicating there are CheckM executables in two different locations (/usr/local/bin/checkm and ~/.locl/bin). Why is this?

If you are still experiencing the error <code>ImportError: No module named cycler</code>, this is an issue with matplotlib. I'm not sure what would case the SyntaxError you have indicated as the line of code is valid and is expected in the CheckM source.

**Comment by piyuranjan** [comment] 2016-04-19 15:54
There is a global (root) version of CheckM (v0.9.7) installed on the server that I use. Server admin did an installation, I think about an year ago. I was trying to update the installation to the latest version (v1.0.5) for my use. Since, I don't have root privileges on the server, I could only do the updates locally. This is why I tried `pip install --user checkm-genome` which made an instance in ~/.local/bin but now none of the executable locations (global/local) were working. Other people on the same server were still able to work with the global version (which was great... phew).

So it turns out, after doing the unsuccessful local upgrade, somehow global CheckM switched to my local python libraries. I had matplotlib installed but it was missing the cycler package. Thanks to your response, I got to understand the problem and updated my local matplotlib. This reinstated the global CheckM. So I am in a workable condition now. :+1:

About the update to v1.0.5 though, it still seems to give me the same problem as in my previous response. I am showing it again in the image below. I now have the matplotlib and pysam (a previous, stable release) installed locally and working on the server. Let me know if you have any leads on this.
![image](https://cloud.githubusercontent.com/assets/2341240/14645803/1c9358da-0625-11e6-91fc-79b4f2e36f61.png)

Again, thanks a lot for helping me resolve this.

**Comment by dparks1134** [comment] 2016-04-20 21:58
I believe the problem is that CheckM requires Python >= 2.7 and < 3.0. The
notation for sets (the curly brackets) is not valid with Python 2.6. Can
you update your version of Python to 2.7.x?

**Comment by piyuranjan** [comment] 2016-04-21 01:08
My server has Python 2.7 installed, I just need to figure out how to make it a default. Still I would recommend adding Python 2.7 as a requirement in the CheckM versions. When I installed using `pip install --user --upgrade checkm-genome`, CheckM source got built in two locations by default `/projects/home/pranjan6/.local/lib/python2.7/site-packages/checkm` and `/projects/home/pranjan6/.local/lib/python2.6/site-packages/checkm` which is something I don't understand given CheckM requires Python >= 2.7. But the binary instance of CheckM in `/projects/home/pranjan6/.local/bin/` was using python 2.6 which is even more confusing. I don't know if you can make something to be compiled specifically to a Python version using pip (Python world is largely unknown to me), but if you can add that as a requirement, that would at the least stop before even putting files in those locations.

In my previous post, I told you that my global instance started working after I updated matplotlib in my local Python. But later it failed during a run with the following error:
![image](https://cloud.githubusercontent.com/assets/2341240/14694807/2ee3f0c4-073a-11e6-908b-a2ec669dbbb8.png)
This I guess means that CheckM (global instance) is not only using my local libs in Python 2.6 but also from 2.7 which makes me feel like the code got splattered across everywhere with the most preferred (and likely the only) installation option provided for CheckM.

Sorry, I don't mean to be rude here but can you please suggest me a way to cleanup all this? I am happy to just use the global instance with the previous libraries.

**Comment by dparks1134** [comment] 2016-04-21 01:28
I haven't done this personally, but pip does have an uninstall command:
https://pip.pypa.io/en/stable/reference/pip_uninstall/

**Comment by dparks1134** [comment] 2016-04-23 22:33
Closed as the issue appear to be related to CheckM dependencies and not CheckM itself.

**Closed by dparks1134** 2016-04-23 22:33 UTC
