### ISSUE TITLE
ERROR: Models must be parsed before identifying HMM hits.

### ISSUE THREAD

**Issue by jcpasion** [Ecogenomics/CheckM#272] opened 2020-07-28 22:50 UTC
Hello,

I installed checkM 1.1.3, and have installed the required tools as well:

Hmmer(v3.3.1)
Prodigal (v2.6.3)
Pplacer (v1.17)

All of these tools are set in PATH, so i can call them from anywhere.

I am running macOS Mojave 10.14.6. 

And I have used setRoot on the dataset provided.

I am trying to run checkm with this command:

checkm lineage_wf genome checkm_output

and I am getting these errors:

[2020-07-28 17:39:55] INFO: CheckM v1.1.3
[2020-07-28 17:39:55] INFO: checkm lineage_wf ./ref_genome/ ./checkm_output/
[2020-07-28 17:39:55] INFO: [CheckM - tree] Placing bins in reference genome tree.
[2020-07-28 17:39:56] INFO: Identifying marker genes in 1 bins with 1 threads:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: 'MarkerGeneFinder' object has no attribute '__reportProgress'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: 'MarkerGeneFinder' object has no attribute '__processBin'
[2020-07-28 17:39:58] INFO: Saving HMM info to file.
[2020-07-28 17:39:58] INFO: Calculating genome statistics for 1 bins with 1 threads:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
    exitcode = _main(fd, parent_sentinel)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: 'BinStatistics' object has no attribute '__reportProgress'
    self = reduction.pickle.load(from_parent)
AttributeError: 'BinStatistics' object has no attribute '__processBin'
[2020-07-28 17:39:59] INFO: Extracting marker genes to align.
[2020-07-28 17:39:59] ERROR: Models must be parsed before identifying HMM hits.

Any help with this? Thanks in advance.

**Comment by dparks1134** [comment] 2020-07-28 23:19
Hi. Sorry, not sure what to suggest. The error messages would suggest it is an issue with CheckM not being able to find certain functions (e.g. `__reportProgress`). It isn't clear why this would be though. Did you install CheckM from pip or source?

**Comment by jcpasion** [comment] 2020-07-28 23:51
I installed CheckM using pip3, following commands from the wiki: pip3 install checkm-genome. Any other information I can give?

**Comment by jcpasion** [comment] 2020-07-29 02:14
![Screen Shot 2020-07-28 at 9 13 50 PM](https://user-images.githubusercontent.com/22204911/88748700-46c52680-d117-11ea-8472-789bc4acc4d8.png)

This is what I see in the directory I installed checkm into.

**Comment by dparks1134** [comment] 2020-07-29 13:21
I'm not sure what to suggest. The installation looks correct. The alternative would be to install CheckM via Conda (https://anaconda.org/bioconda/checkm-genome) though please note that I don't maintain the Conda install or to use CheckM at KBase (https://kbase.us/applist/apps/kb_Msuite/run_checkM_lineage_wf).

**Comment by muhammadnaufal1203** [comment] 2020-08-03 07:02
![image](https://user-images.githubusercontent.com/69138840/89154733-0c85da00-d59a-11ea-87cc-49d57bbd0fc3.png)
i got the same problem, However an error show off "Models must be parsed before identifying HMM hits"
i installed checkm using Conda.
Any suggestions?

**Comment by muhammadnaufal1203** [comment] 2020-08-03 08:28
![image](https://user-images.githubusercontent.com/69138840/89162131-2decc300-d5a6-11ea-90b6-999600eb51df.png)
hi, i got the same problem. the screen showed this message after running the command.

Any suggestion? i installed my checkm using conda environmnet

**Comment by jtay133** [comment] 2020-08-07 07:17
I have a similar but probably different issue. I have 6 MAGs which I need to re-run through CheckM.
Three MAGs work fine, but the other three do not produce results.
I can see no issue with the fasta files and CheckM has worked on them in the past. I  get the same non-result using the lineage and taxonomy wfs and I have tried using different versions of python.  

using python/3.7.3 or 3.7.8, hmmer/3.3, pplacer/1.1.alpha19, prodigal/2.6.3

This is what happens:

[2020-08-06 23:52:29] INFO: CheckM v1.1.2
[2020-08-06 23:52:29] INFO: checkm lineage_wf -f ./SCG/SCG.txt -t 1 -x fa ./MAGs/MAGs2/MAGs3 ./SCG
[2020-08-06 23:52:29] INFO: [CheckM - tree] Placing bins in reference genome tree.
[2020-08-06 23:52:30] INFO: Identifying marker genes in 3 bins with 1 threads:
    Finished processing 0 of 3 (0.00%) bins.
Process Process-2:
Traceback (most recent call last):
  File "/apps/python/3.7.3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/apps/python/3.7.3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/apps/python/3.7.3/lib/python3.7/site-packages/checkm/markerGeneFinder.py", line 115, in __processBin
    prodigal.run(binFile, bNucORFs)
  File "/apps/python/3.7.3/lib/python3.7/site-packages/checkm/prodigal.py", line 104, in run
    prodigalParser = ProdigalGeneFeatureParser(gffFile)
  File "/apps/python/3.7.3/lib/python3.7/site-packages/checkm/prodigal.py", line 191, in __init__
    self.__parseGFF(filename)
  File "/apps/python/3.7.3/lib/python3.7/site-packages/checkm/prodigal.py", line 220, in __parseGFF
    start = int(lineSplit[3])
IndexError: list index out of range

[2020-08-06 23:52:33] INFO: Saving HMM info to file.
[2020-08-06 23:52:33] INFO: Calculating genome statistics for 3 bins with 1 threads:
    Finished processing 0 of 3 (0.00%) bins.
    Finished processing 1 of 3 (33.33%) bins.
    Finished processing 2 of 3 (66.67%) bins.
    Finished processing 3 of 3 (100.00%) bins.
[2020-08-06 23:52:33] INFO: Extracting marker genes to align.
[2020-08-06 23:52:33] ERROR: Models must be parsed before identifying HMM hits.

  Controlled exit resulting from an unrecoverable error or warning.

Any idea whats happening?
Thanks, Jess

**Comment by dparks1134** [comment] 2020-08-07 13:52
Hi. Can you send me the bins (FASTA files) that aren't processing correctly and I will check if they work on my end? It would be good to establish if the problem is the bins or the installation. You can send the files to donovan.parks[at]gmail.com.

**Comment by jtay133** [comment] 2020-08-08 04:06
I was getting this error message, it turned out there were new lines in my fasta file sequences. Once I reformatted my fastas it worked fine

**Comment by muhammadnaufal1203** [comment] 2020-08-10 03:51
> 
> 
> I was getting this error message, it turned out there were new lines in my fasta file sequences. Once I reformatted my fastas it worked fine

Hi, thanks for the replay. did you installed checkm using conda env? how you reformatted the fasta file? i still dont get it.

**Comment by dparks1134** [comment] 2020-08-10 13:24
Hi. The issue is as described by jtay133 (thanks!). This can be addressed by making sure your FASTA file(s) have Linux-style and not Windows-style line endings. A workaround to this issue has also  been implemented in CheckM v1.1.3.

**Comment by muhammadnaufal1203** [comment] 2020-08-11 07:15
thank you for the replay all ..
my checkm is workin now ..
you ca use this command to reformated the windows  vrsion of fasta to linux format

$ sed -e 's/\r$//' inputfile > outputfile              # DOS  to UNIX (removing CRs on Linux based OS that use GNU extensions)

good luck

**Closed** 2020-08-11 14:18 UTC

**Comment by jorondo1** [comment] 2022-02-14 19:57
Hi,
I am having the exact same issue here and the proposed solution did not resolve it. Using CheckM 1.1.3, I also get **the AttributeError: 'MarkerGeneFinder' object has no attribute '__processBin'** several times

here is the log

[2022-02-14 14:51:11] INFO: CheckM v1.1.3
[2022-02-14 14:51:11] INFO: checkm lineage_wf -t 4 -x fa bins/test checkm
[2022-02-14 14:51:11] INFO: [CheckM - tree] Placing bins in reference genome tree.
[2022-02-14 14:51:11] WARNING: Skipping bin bin.lowDepth.fa as it has a size of 0 bytes.
[2022-02-14 14:51:14] INFO: Identifying marker genes in 9 bins with 4 threads:
[2022-02-14 14:51:17] INFO: Saving HMM info to file.
[2022-02-14 14:51:17] INFO: Calculating genome statistics for 9 bins with 4 threads:
[2022-02-14 14:51:19] INFO: Extracting marker genes to align.
[2022-02-14 14:51:19] ERROR: Models must be parsed before identifying HMM hits.

ANy idea what else could cause this ? It's the same with tree (haven't tested anything else yet)

**Comment by dparks1134** [comment] 2022-08-03 22:35
Hi. This is a known issue when using MacOS and Python >=3.8. This has been fixed in the latest release of CheckM (v1.2.1) which is now available on PyPi. I don't maintain the BioConda install of CheckM, but hopefully this will be updated to v1.2.1 shortly.

**Comment by raw937** [comment] 2022-10-06 18:54
Same issue. 

[2022-10-06 14:52:39] INFO: Extracting marker genes to align.
[2022-10-06 14:52:39] ERROR: Models must be parsed before identifying HMM hits.

  Controlled exit resulting from an unrecoverable error or warning.

**Comment by wangzefei446** [comment] 2023-02-24 05:27
[2023-02-24 13:19:10] INFO: Saving HMM info to file.
[2023-02-24 13:19:10] INFO: Calculating genome statistics for 1 bins with 1 threads:
    Finished processing 1 of 1 (100.00%) bins.
[2023-02-24 13:19:10] INFO: Extracting marker genes to align.
[2023-02-24 13:19:10] ERROR: Models must be parsed before identifying HMM hits.

what should i do?

**Comment by wangzefei446** [comment] 2023-02-24 05:30
> 



> Hi, I am having the exact same issue here and the proposed solution did not resolve it. Using CheckM 1.1.3 on Mac OS X 10.14.6, I also get **the AttributeError: 'MarkerGeneFinder' object has no attribute '__processBin'** several times
> 
> here is the log
> 
> [2022-02-14 14:51:11] INFO: CheckM v1.1.3 [2022-02-14 14:51:11] INFO: checkm lineage_wf -t 4 -x fa bins/test checkm [2022-02-14 14:51:11] INFO: [CheckM - tree] Placing bins in reference genome tree. [2022-02-14 14:51:11] WARNING: Skipping bin bin.lowDepth.fa as it has a size of 0 bytes. [2022-02-14 14:51:14] INFO: Identifying marker genes in 9 bins with 4 threads: [2022-02-14 14:51:17] INFO: Saving HMM info to file. [2022-02-14 14:51:17] INFO: Calculating genome statistics for 9 bins with 4 threads: [2022-02-14 14:51:19] INFO: Extracting marker genes to align. [2022-02-14 14:51:19] ERROR: Models must be parsed before identifying HMM hits.
> 
> ANy idea what else could cause this ? It's the same with tree (haven't tested anything else yet)

Have you sovled this problem?

**Comment by GuyTadmor-28** [comment] 2023-06-25 10:58
CheckM data: /home/labs/zeevid/guyta/.checkm
[CheckM - tree] Placing bins in reference genome tree.
Identifying marker genes in 1 bins with 1 threads:
Saving HMM info to file.
Calculating genome statistics for 1 bins with 1 threads:
Extracting marker genes to align.
 Models must be parsed before identifying HMM hits.

Hi, I'm facing the same issue. Do you know if anyone sort it out?
I use Python 3.7 on a Linux machine, CheckM (v1.2.2) installed using pip as recommended. 

Cheers

**Comment by cuongngh** [comment] 2024-08-10 16:00
I have the same issue:
###
[2024-08-10 17:58:00] INFO: [CheckM - Test] Processing E.coli K12-W3310 to verify operation of CheckM.
[2024-08-10 17:58:00] INFO: [Step 1]: Verifying tree command.
[2024-08-10 17:58:00] INFO: [CheckM - tree] Placing bins in reference genome tree.
[2024-08-10 17:58:00] INFO: Identifying marker genes in 1 bins with 1 threads:
[2024-08-10 17:58:09] INFO: Saving HMM info to file.
[2024-08-10 17:58:09] INFO: Calculating genome statistics for 1 bins with 1 threads:
[2024-08-10 17:58:10] INFO: Extracting marker genes to align.
[2024-08-10 17:58:10] INFO: Parsing HMM hits to marker genes:
    Finished parsing hits for 1 of 1 (100.00%) bins.
[2024-08-10 17:58:10] INFO: Extracting 43 HMMs with 1 threads:
[2024-08-10 17:58:11] INFO: Aligning 43 marker genes with 1 threads:
[2024-08-10 17:58:11] ERROR: Make sure pplacer is on your system path.

  Controlled exit resulting from an unrecoverable error or warning.
###
In my case, I have silicon MacBook Pro, and dependencies were installed manually, and checkm-genome was installed with pip, not pip3. 

Any suggestions would be appreciated.
Cheers,

**Comment by MatS792** [comment] 2024-10-02 17:31
I hope it will help.
I solved **ERROR: Models must be parsed before identifying HMM hits** using:
checkm data setRoot path/to/your/checkm_data/

**Comment by cuongngh** [comment] 2024-10-04 06:04
> I hope it will help. I solved **ERROR: Models must be parsed before identifying HMM hits** using: checkm data setRoot path/to/your/checkm_data/

Thank you so very much. I will try this.

**Comment by priscalim00** [comment] 2024-10-07 18:40
Hi, I recently encountered this issue as well and `checkm data setRoot` didn't work for me but `export CHECKM_DATA_PATH=/path/to/checkm_data/` worked. Wanted to share in case others are needing alternative options to try.

**Comment by ZING-ZMJ** [comment] 2024-10-15 07:53
encountered with the same issue, anyone know how to fix it? 
--------------------------------------------------------------------------
[2024-10-15 15:48:35] INFO: CheckM v1.2.3
.
.
.
[2024-10-15 15:48:35] ERROR: hmmsearch exited with code: 34304

[2024-10-15 15:48:35] INFO: Saving HMM info to file.
[2024-10-15 15:48:35] INFO: Calculating genome statistics for 1 bins with 8 threads:
    Finished processing 1 of 1 (100.00%) bins.
[2024-10-15 15:48:36] INFO: Extracting marker genes to align.
[2024-10-15 15:48:36] ERROR: Models must be parsed before identifying HMM hits.

  Controlled exit resulting from an unrecoverable error or warning.
--------------------------------------------------------------------------------

**Comment by ZING-ZMJ** [comment] 2024-10-15 07:54
> ## encountered with the same issue, anyone know how to fix it?
> [2024-10-15 15:48:35] INFO: CheckM v1.2.3 . . . [2024-10-15 15:48:35] ERROR: hmmsearch exited with code: 34304
> 
> [2024-10-15 15:48:35] INFO: Saving HMM info to file. [2024-10-15 15:48:35] INFO: Calculating genome statistics for 1 bins with 8 threads: Finished processing 1 of 1 (100.00%) bins. [2024-10-15 15:48:36] INFO: Extracting marker genes to align. [2024-10-15 15:48:36] ERROR: Models must be parsed before identifying HMM hits.
> 
> ## Controlled exit resulting from an unrecoverable error or warning.

checkm test runs well, but when comes to my own data it came up with this issue

**Comment by Echo-2024** [comment] 2024-10-16 14:11
> > ## encountered with the same issue, anyone know how to fix it?
> > [2024-10-15 15:48:35] INFO: CheckM v1.2.3 . . . [2024-10-15 15:48:35] ERROR: hmmsearch exited with code: 34304
> > [2024-10-15 15:48:35] INFO: Saving HMM info to file. [2024-10-15 15:48:35] INFO: Calculating genome statistics for 1 bins with 8 threads: Finished processing 1 of 1 (100.00%) bins. [2024-10-15 15:48:36] INFO: Extracting marker genes to align. [2024-10-15 15:48:36] ERROR: Models must be parsed before identifying HMM hits.
> > ## Controlled exit resulting from an unrecoverable error or warning.
> 
> checkm test runs well, but when comes to my own data it came up with this issue

You may try the commands which were recommended by users priscalim00 or MatS792. 
Add the code before you Run code, and this was my example. Hope it will help.
export CHECKM_DATA_PATH=/path/to/my_checkm_database   # set the db path
dRep dereplicate  ...
