### ISSUE TITLE
checkm tetra issue- No handlers could be found for logger "root"

### ISSUE THREAD

**Issue by cssulliv** [Ecogenomics/CheckM#222] opened 2019-09-04 02:05 UTC
Hi,

I am trying to run checkm tetra but keep getting the following outputs below. 

[2019-09-04 02:00:35] INFO: [CheckM - tetra] Calculating tetranucleotide signature of sequences.
[2019-09-04 02:00:35] INFO: Determining tetranucleotide signature of each sequence.
No handlers could be found for logger "root"
  Controlled exit resulting from an unrecoverable error or warning.

I am not entirely sure what type of error this is and how to fix it.

Would you have an idea of what is causing checkm tetra to produce the error?

My script is attached below.

`checkm tetra -t 3 /home/cssulliv/pelagibacter_lts/001_2011Samples/01_RAWDATA/11_CheckM/NitroMAGs_1362A_B_round2_refined /home/cssulliv/pelagibacter_lts/001_2011Samples/01_RAWDATA/11_CheckM/tetra_profile_Nitro`

**Comment by sentausa** [comment] 2019-09-06 08:34
Hi,

I got the same error after running lineage_wf command with called genes in faa:

```
$ checkm lineage_wf --genes -t 48 -x faa . CheckMfaa
[2019-09-06 10:20:57] INFO: CheckM v1.0.18
[2019-09-06 10:20:57] INFO: checkm lineage_wf --genes -t 48 -x faa . CheckMfaa
[2019-09-06 10:20:57] INFO: [CheckM - tree] Placing bins in reference genome tree.
No handlers could be found for logger "root"

  Controlled exit resulting from an unrecoverable error or warning.
```
Yesterday I ran lineage_wf using the genome it worked fine. And FYI, I installed checkm using pip install --local.

Thanks for any help.

**Comment by cssulliv** [comment] 2019-09-07 00:46
I installed checkM using conda and am running it through our university server/cluster. I am unfortunately still getting the error. :/

**Comment by dparks1134** [comment] 2019-10-30 19:49
I am unable to reproduce the issue on my end. This is likely an installation issue though it is unclear what it would be.

**Comment by kjojess** [comment] 2019-11-03 20:08
I am also getting this error after installing with bioconda. 
[2019-11-03 15:05:13] INFO: CheckM v1.0.18
[2019-11-03 15:05:13] INFO: checkm tree -x fa bins/ /data/data_GATech/EcoZUR/metagenomes/checkm/checkm_tree_out
[2019-11-03 15:05:13] INFO: [CheckM - tree] Placing bins in reference genome tree.
No handlers could be found for logger "root"

The checkm test ran successfully, so I'm not sure what the problem is.

**Comment by dparks1134** [comment] 2019-11-05 22:31
This should be fixed in the next release which will be available on Dec. 1.

**Closed by dparks1134** 2019-11-05 22:31 UTC
